astra:
  api:
    application-token: AstraCS:IAAFgcfxyOKLNeKbYrshlxMT:221f331224eb0e9fef75f1c95644a9ddf251d9904fc900091098a3b7b62ca615
    database-id: 273da712-6791-4d6f-97a8-c1198f669817
    database-region: us-east1
    cross-region-failback: off
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DEMO_KEYSPACE:demo}

server:
  port: 8082

astra-demo:
  embedding-service:
    url: ${ASTRA_DEMO_EMBEDDING_SERVICE_URL:http://localhost:5000}
    dims:
      dense: ${ASTRA_DEMO_EMBEDDING_SERVICE_DIMS_DENSE:768}
      multi: ${ASTRA_DEMO_EMBEDDING_SERVICE_DIMS_MULTI:128}
  entry-ttl: ${ASTRA_DEMO_ENTITY_TTL:86400}
  share-texts: ${ASTRA_DEMO_SHARE_TEXTS:false}

spring:
  threads:
    virtual:
      enabled: true
