astra:
  api:
    application-token: ${ASTRA_DEMO_TOKEN:AstraCS:IAAFgcfxyOKLNeKbYrshlxMT:221f331224eb0e9fef75f1c95644a9ddf251d9904fc900091098a3b7b62ca615}
    database-id: ${ASTRA_DEMO_DB_ID:273da712-6791-4d6f-97a8-c1198f669817}
    database-region: ${ASTRA_DEMO_DB_REGION:us-east1}
    cross-region-failback: off
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: demo

server:
  port: 8082

astra-demo:
  embedding-service:
    url: http://localhost:5000
    dims:
      dense: 768
      multi: 128
  entry-ttl: 86400
  share-texts: false

spring:
  threads:
    virtual:
      enabled: true
