astra:
  api:
    application-token: ${ASTRA_DEMO_DB_TOKEN}
    database-id: ${ASTRA_DEMO_DB_ID}
    database-region: ${ASTRA_DEMO_DB_REGION}
    cross-region-failback: off
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DEMO_DB_KEYSPACE}

server:
  port: 8082

astra-demo:
  embedding-service:
    url: http://localhost:5000
    dims:
      dense: 768
      multi: 128
  entry-ttl: 86400
  share-texts: false

spring:
  threads:
    virtual:
      enabled: true
